version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/go/src/github.com/antonybudianto/go-starter"
      - "/go/src/github.com/antonybudianto/go-starter/vendor"
